### ISSUE TITLE
CompletionStage asserts about failed state should fail when not Done, and only join() else

### ISSUE THREAD

**Issue by tkruse** [assertj/assertj-core#1149]
`hasFailed()` assertion currently passes when the Future/CompletionStage is not yet done, causing brittle tests and race conditions. `hasFailedWithThrowableThat()` on the other hand joins, so it's also an inconsistency.   hasFailedWithThrowableThat() should only join() when done. joining else may cause infinitely running tests, which is undesirable even if it's the original test cases fault.

* [x]  hasFailed() should fail when not done.
* [ ] hasNotFailed() should fail when not done.
* [x]  hasFailedWithThrowableThat() should only join() when done. 

Discussed in #1010

**Comment by joel-costigliola** [comment]
I need to think about this one to make that it follows the semantics of the `CompletionStage`

**Comment by pswiatowski** [comment]
Two of three methods works as expected in the description: method hasFailed fails when not Done,
hasFailedWithThrowableThat() join when done.

We needed to cover only hasNotFailed method which should fail when not done.

**Comment by joel-costigliola** [comment]
As noted by @pswiatowski `hasFailed` assertion does not pass (as expected)  when the future under test is not done as per this test:
```java
  @Test
  public void assertion_should_fail_if_completable_future_is_incomplete() {
    CompletableFuture<String> future = new CompletableFuture<>();

    assertThatThrownBy(() -> assertThat(future).hasFailed()).isInstanceOf(AssertionError.class)
                                                            .hasMessage(shouldHaveFailed(future).create());
  }
```

`hasFailedWithThrowableThat` only joins if the future has failed which we know is done.

Last point: should `hasNotFailed()` fail when the future is not done ?
I would say that you can only know whether a future has failed after it is done.

@tkruse is the problem you are reporting here is about brittle test ?

**Comment by tkruse** [comment]
I agree hasNotFailed should fail when the future is not done.

Else indeed with bad test design, tests will sometimes pass and sometimes not, depending on race conditions. (brittleness).

**Comment by joel-costigliola** [comment]
Well then there is a problem somewhere in the current implementation since `hasNotFailed` checks the opposite condition of `hasFailed` so if one is correct the other one should be.

I'll think about it tomorrow with afresh mind ...

**Comment by tkruse** [comment]
hasFailed and HasNotFailed can be direct opposites, but only under the additional assumption of isDone().

**Comment by joel-costigliola** [comment]
Since `hasFailed` checks that the future under test is completed exceptionally (but not cancelled) this means the future is done according to [CompletableFuture.html#isDone](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#isDone--), if we want `hasNotFailed` to check the opposite condition then we can't require the future to be done.

I realized the point I made was unclear after your reply:

>  you can only know whether a future has failed after it is done.

what I wanted to say is that if a future is not done, you can't say that it has failed since to check for failure you need it to be done => a future not done has not failed but it might eventually after being done.

Note that `hasFailed` and `hasNotFailed` don't call any methods to make the future to be done.

At this point my conclusion is that the API is consistent but whether it is really useful is another thing.

Back to your concern, do I understand correctly your problem if I say you want the future under test to be done to avoid brittle tests?

I'll finish by saying that I wonder if adding `hasFailed` and `hasNotFailed` was good idea, `hasFailed` was simply a shortcut for `isCompletedExceptionally()` + `isNotCancelled()` (something users can do by themselves easily) and `hasNotFailed` the opposite ...

**Comment by tkruse** [comment]
I agree that it is consistent if `hasFailed` and `hasNotFailed` both pass for a future that is not done. 

I think this is not as useful as having both of them fail on futures that are not done yet.

A test like

    assertThat(future).hasNotFailed();

will pass for a future that is still in flight, hiding a bug. Developers would have to remember to check for isDone().

Maybe it is wrong to say that this causes brittleness, the brittleness of a test would be caused by the developer passing a future that will complete concurrently to the assert. It is better to say that this assert does not help detecting brittle tests, and may pass tests that the developer intended to fail, hiding bugs.

To avoid brittleness, developers should always pass a done future to assertJ (until a waitForDone()) method exists, or pass a CompletionStage that is not done and will not concurrently complete in the test, using assertThat(foo).isNotDone() only. I think assertj design should support this best practice. Passing in a Future that is not done to hasFailed() or hasNotFailed() should be considered an InvalidArgument maybe.

**Comment by joel-costigliola** [comment]
I quite like `waitForDone(long timeoutInMs)` that makes it obvious the test will wait for the future to be done.

```
assertThat(future).waitForDone(500)
                  .hasNotFailed();
```
another option (less obvious IMO):
```
assertThat(future).hasNotFailed(500);
```

**Comment by tkruse** [comment]
Sure, we discussed it some time ago here: #1150, but it is a bit independent of the issue here.

**Comment by joel-costigliola** [comment]
Is there something to fix in this issue if we address #1150 ? If so what is it ?

**Comment by tkruse** [comment]
Even if there was a waitFor, my previous comment:

> I agree that it is consistent if hasFailed and hasNotFailed both pass for a future that is not done.
> 
> I think this is not as useful as having both of them fail on futures that are not done yet.
> [...]
>  Passing in a Future that is not done to hasFailed() or hasNotFailed() should be considered an InvalidArgument maybe.

**Comment by joel-costigliola** [comment]
> I agree that it is consistent if hasFailed and hasNotFailed both pass for a future that is not done.

This is not what I was saying, they can't both pass on a the same future as they are **opposite** assertions. 
I'm not keen to change `hasNotFailed` because it would mean it is not the opposite of `hasFailed` anymore, this is why I think adding a timeout parameters is a solution as it provides the missing feature without breaking anything.

**Comment by tkruse** [comment]
Hmm... If both accept in-flight futures we get:

     Future        hasFailed   hasNotFailed
     NotDone      pass            pass
     suceeded     fail            pass
     failed       pass            fail
     cancelled    ?               ?

So here they would both pass on the same future.

If both reject in-flight futures, that is

     Future        hasFailed   hasNotFailed
     NotDone      fail            fail
     suceeded     fail            pass
     failed       pass            fail
     cancelled    ?               ?

Here they would not both pass on the same future (but they could fail on the same future).

If you want them to always be opposite assertions, then indeed one has to pass on an in-flight future, and the other has to fail on it. But since they have the same natural language structure (has...), developers would have to get confused over which one checks isDone() and which one does not.

So I still think they should both reject in-flight futures.

Adding a timeout parameter to both hasFailed and hasNotFailed is similar to rejecting in-flight future (which could be seen as having a default timeout of 0). Adding a timeout parameter to just one of both is confusing again (and to make sure they are boolean opposites you'd need a bigger truth table for cases of timeout and non-timeout).

**Comment by joel-costigliola** [comment]
@tkruse I'm not convinced, I still think that `hasNotFailed` should be the opposite of `hasFailed`, not doing so will be confusing (otherwise we need to rename `hasNotFailed` to something else).

One AssertJ design principle is to avoid modifying the object under test unless being explicit about it, so joining a future should be avoided (and `hasFailedWithThrowableThat` does that but since it checks the future has failed then joining does not have any side effects).

Your table shows that the result of `hasFailed` on cancelled future is `?`, but since `hasFailed` is a simple shortcut for `isCompletedExceptionally().isNotCancelled()` then the assertion is not going to pass.

We can clarify the javadoc by adding a table like yours showing the different outcomes for `hasFailed` and `hasNotFailed`.

So to be clear:

-  `hasFailed` and `hasNotFailed` behavior won't change
-  `hasFailed` and `hasNotFailed` javadoc needs to be clearer
- we can provide alternatives with timeout when useful.

**Comment by tkruse** [comment]
Actually, the javadoc for `hasNotFailed` is already very clear.

Looking at the other asserts, there is:

    isDone
    isNotDone
    isCompletedExceptionally
    isNotCompletedExceptionally
    isCancelled
    isNotCancelled
    isCompleted
    isNotCompleted
    hasFailed
    hasNotFailed

Possibly changing from hasFailed and hasNotFailed to isFailed and isNotFailed would make it clearer that isNotFailed also accepts a non-done Future, linguistically not talking about events in the past, but only about the current state.

But anyway, this issue can be closed any way you like, it seems my issue is a mere design preference, not an objective inconsistency.

**Comment by joel-costigliola** [comment]
This issue is out of date as `hasFailed` has been deprecated in favor of  [`failsWithin`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractCompletableFutureAssert.html#failsWithin(java.time.Duration)). [hasNotFailed](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractCompletableFutureAssert.html#hasNotFailed()) has been deprecated too.
