### ISSUE TITLE
jsr305 support for kotlin

### ISSUE THREAD

**Issue by xenoterracide** [assertj/assertj-core#1414]
#### Summary

probably pretty low priority, but it would be nice if assertj was annotated with jsr305 annotations so that kotlin could use them to tell where things are(n't) nullable.

https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support

**Comment by joel-costigliola** [comment]
Is jsr305 part of the JDK ? 
If not, that will not be possible as assertj-core has a no dependency policy.

**Comment by xenoterracide** [comment]
it is not, however, you can apply it and then not provide the jar, and it's not a runtime dependency. Essentially making it dependency-less as far as your users are concerned (as it doesn't add one).

**Comment by joel-costigliola** [comment]
Sure then.

**Comment by checketts** [comment]
I've added this support in other projects. Would you be interested in a contribution for this?

**Comment by joel-costigliola** [comment]
@checketts that would be great! thanks.

**Comment by scordio** [comment]
I would not continue with jsr305 [due to issues with Java 9 modules](https://blog.codefx.org/java/jsr-305-java-9/) and we should probably remove the existing occurrences. Some libraries already started to opt out of it (e.g., google/guava#2960).

[The Checker Framework](https://checkerframework.org/) could be a viable alternative which [seems to be understood by Kotlin](https://github.com/JetBrains/kotlin/blob/master/core/descriptors.jvm/src/org/jetbrains/kotlin/load/java/JvmAnnotationNames.kt#L28).

@joel-costigliola @xenoterracide @checketts thoughts?

**Comment by joel-costigliola** [comment]
I'm happy with removing jsr 305 since it causes more issues than benefits

**Comment by joel-costigliola** [comment]
closing since https://github.com/assertj/assertj-core/pull/1739 has been merged
