### ISSUE TITLE
Collection print does not work properly when collection extends AtomicInteger

### ISSUE THREAD

**Issue by matejdro** [assertj/assertj-core#1483]
#### Summary

RxJava exposes [its own internal collections for test, which extend AtomicInteger](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/VolatileSizeArrayList.java).

However, when asserting on that list, AssertJ will detect that list is of type AtomicInteger and print integer value instead of list contents on errors.

#### Example

Add to gradle:

```
compile "io.reactivex.rxjava2:rxjava:2.2.8"
compile "org.assertj:assertj-core:3.11.1"
```

Execute:
```java
Flowable<String> textObservable = Flowable.just("A", "B", "C");

List<String> receivedEntries = textObservable.test().values();

// Prints [A, B, C] normally
System.out.println(receivedEntries);

// Prints AtomicInteger(3) when assert fails
assertThat(receivedEntries).isEmpty();
```

**Comment by joel-costigliola** [comment]
This is due to [`StandardRepresentation.toStringOf](https://github.com/joel-costigliola/assertj-core/blob/b82b86b2c54bb33c09103744ea0d7af4b37b4dee/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L160) that looks for `AtomicInteger` before `Collection`.

One simple fix would be to change the order by checking `Collection` before `AtomicInteger` (and more generally most specific types should be checked first, although it is not clear how to classify the types).

You have another option: [registering a custom representation](https://assertj.github.io/doc/#assertj-core-representation) to specify how to format `VolatileSizeArrayList`. 
If you choose to [register a Representation](https://assertj.github.io/doc/#assertj-core-custom-representation-default-global-scope), you will be impacted by https://github.com/joel-costigliola/assertj-core/issues/1361 which will slightly change the way to register a Representation.
