### ISSUE TITLE
Allow providing BiPredicate for equals override

### ISSUE THREAD

**Issue by shollander** [assertj/assertj-core#1561]
I like the feature that allows the user to override the `equals()` method for comparison.
However, the current api creates unnecessary complications and appears to be a misuse of `Comparator`. `Comparator`s are intended for ordering objects, not testing equality. The contract for `Comparator.compareTo()` doesn't even require it to be consistent with `equals()`.
It would be simpler to allow the user to supply a `BiPredicate` to test for equality. This would allow users to simplify implementation (only two possible return values instead of three) and provide a cleaner api.

**Comment by joel-costigliola** [comment]
@shollander can you give an example ?

**Comment by shollander** [comment]
@joel-costigliola I was thinking of something like this (using one of your examples):
```java
public class TolkienCharacter {
  String name;
  double height;
}

@FunctionalInterface
public interface EqualsPredicate<T> extends BiPredicate<T, T> {
}

TolkienCharacter frodo = new TolkienCharacter("Frodo", 1.2);
TolkienCharacter tallerFrodo = new TolkienCharacter("Frodo", 1.3);
TolkienCharacter reallyTallFrodo = new TolkienCharacter("Frodo", 1.9);

EqualsPredicate<Double> closeEnough = (d1, d2) -> Math.abs(d1 - d2) <= 0.5;

// assertion succeeds
assertThat(frodo).usingRecursiveComparison()
                 .withEqualsForFields(closeEnough, "height")
                 .isEqualTo(tallerFrodo);

assertThat(frodo).usingRecursiveComparison()
                 .withEqualsForFields(closeEnough, Double.class)
                 .isEqualTo(tallerFrodo);
```

**Comment by joel-costigliola** [comment]
You have a point for `Comparator` over `EqualsPredicate` but I don't find the difference between the two approaches to be huge, I mean instead of:
```java
EqualsPredicate<Double> closeEnough = (d1, d2) -> Math.abs(d1 - d2) <= 0.5;
```
you write
```java
Comparator<Double> closeEnough = (d1, d2) -> Math.abs(d1 - d2) <= 0.5 ? 0 : 1;
```

> The contract for Comparator.compareTo() doesn't even require it to be consistent with equals()

True but if you define your comparator, it's up to you. Moreover if you use a comparator it's because `equals` does not suit you.

Having said that we can consider `withComparatorForFields` to accept an `EqualsPredicate` and maybe rename the method to something more generic, what we want avoid though is supporting both `withComparatorForFields` and `withEqualsForFields`.

**Comment by shollander** [comment]
If you don't fully implement the `Comparator` (i.e. all three return values) then you are right, there is not much *practical* difference. But that just means that you are taking the `Comparator` interface and twisting it to suit your needs. My point was that as an API, `Comparator` doesn't really make sense here.

**Comment by joel-costigliola** [comment]
The more I think about it, the more I agree with you, we logically only need an equal function.

Since the recursive api is still in beta, I think we could deprecate `withComparatorForFields` for `withEqualsForFields`.

One thing `EqualsPredicate` should provide is an optional description to be displayed in the error message to let user know what equal strategy was applied on fields (as we do now with comparators).

**Comment by filiphr** [comment]
Thinking out loud. You could add a default method to the `EqualsPredicate` that would give you back a description. This can be in addition to calling the method with the predicate and its description. 

I envision this being used for such shared predicates. So you can define the description on the predicate

**Comment by joel-costigliola** [comment]
@filiphr  Yes I was thinking about that

**Comment by G3zz** [comment]
The use of `BiPredicate` instead of `Comparator` would be very useful when making recursive comparisons between objects of different types.

**Comment by scordio** [comment]
Related to #1904

**Comment by joel-costigliola** [comment]
Done in #1904 and documented here https://assertj.github.io/doc/#assertj-core-recursive-comparison-comparators
