### ISSUE TITLE
Comparing of Boxed vs. Unboxed Array broken

### ISSUE THREAD

**Issue by nioertel** [assertj/assertj-core#1948]
#### Summary
Before PR #1767 (specifically commit [76762a3664b3af2101d580355a05c6f0b3aa46cc](../commit/76762a3664b3af2101d580355a05c6f0b3aa46cc)) it was possible to compare a boxed with an unboxed array.
This was because org.assertj.core.util.areEqualArrays was comparing entry by entry which took care of automatic boxing/unboxing.
This functionality is broken and I'm not sure whether this was intentional. It's causing quite some refactoring efforts on our side to upgrade and I would argue that the old behaviour was quite useful.

#### Example

```java
// fails with assertj 3.16.1; succeeds with 3.13.2; probably broken since 13.15.1
@Test
void testCompareArrays() {
	long[] array1 = new long[] { 2L, 2L };
	Long[] array2 = new Long[] { 2L, 2L };
		
	BDDAssertions.assertThat(array1).isEqualTo(array2);
}
```

**Comment by scordio** [comment]
My initial feeling is that the old behavior was violating the language desing, which [supports boxing/unboxing for primitive types](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.7) but not for the corresponding arrays.

Also, IntelliJ fires an [`assertEquals`() between objects of inconvertible types](https://www.jetbrains.com/help/idea/list-of-java-inspections.html#junit) warning with the example above. Indeed, `org.junit.jupiter.api.Assertions.assertEquals` fails similarly.

However, I understand the convenience of the previous behavior.

Instead of having it behind an `equals` check, my proposal would be to make it explicit adding the overloaded version of the assertions in the `contains` family which would support boxed arrays. E.g., in `AbstractLongArrayAssert` we would add:

```
  public SELF containsExactly(Long[] values) {
    arrays.assertContainsExactly(info, actual, values);
    return myself;
  }
```

which would allow:

```
  @Test
  void testCompareArrays() {
    long[] array1 = new long[] { 2L, 2L };
    Long[] array2 = new Long[] { 2L, 2L };

    assertThat(array1).containsExactly(array2);
  }
```

@nioertel would this approach fit your needs?

@joel-costigliola what's your opinion about it? As a bonus topic, is it something to consider for the recursive comparison api improvements?

**Comment by nioertel** [comment]
Valid point.
Adding the Long[] version to AbstractLongAssert could be handy, however it should then also be added to the other Abstract(Primitive)ArrayAsserts for consistency of the API.
Also the other way round is not possible as ObjectArrayAssert can't really deal with this situation.

In any case we refactored our affected test code, so I'm okay with the breaking change now.

**Comment by scordio** [comment]
> Adding the Long[] version to AbstractLongAssert could be handy, however it should then also be added to the other Abstract(Primitive)ArrayAsserts for consistency of the API.

Yes, definitely.

>  Also the other way round is not possible as ObjectArrayAssert can't really deal with this situation.

Right, there is no way to have a nice API on `AbstractObjectArrayAssert`.

From user point of view, the "easiest" workaround I found to fullfill this use case is the following:

```java
  @Test
  void testCompareArrays() {
    long[] array1 = new long[] { 2L, 2L };
    Long[] array2 = new Long[] { 2L, 2L };

    assertThat(array2).containsExactly(Arrays.stream(array1).boxed().toArray(Long[]::new));
  }
```

We could add additional `AbstractArrayAssert` children to cover the wrapper arrays if the community starts asking for this, but at the moment it seems overkilling.

**Comment by joel-costigliola** [comment]
I agree with @scordio approach, it's going to be a bit of work to do all the primitive types but that's fine.

I think we can consider allowing comparing long[] to Long[] in the recursive comparison as the philosophy of this comparison is to focus on the data (types are less important unless you enable strict type checking).

**Comment by joel-costigliola** [comment]
I'll start on this one for long/Long.
