### ISSUE TITLE
Add AbstractCharacterSequenceAssert#hasCodePoints(I) 

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2088]
#### Summary

The `AbstractCharacterSequenceAssert#hasSize(I)` has been stated that it used the `String#length()` method which is fine.

In a case of a String of non-single unicode literals we need to assert the `CharSequence#codePoints()` method.

```java 
    // works as documented
    assertThat("µµµ").isEqualTo("µµµ");
    assertThat("µµµ").hasSize(3);
    assertThat("µµµ").inUnicode().hasSize(3);

    final String literal = "\uD840\uDC00";
    assertThat(literal).hasSize(2);
    assertThat(literal).inUnicode().hasSize(2);

    // the liternal represents a single supplementary character 
    // see https://www.fileformat.info/info/unicode/char/20000/index.htm
    assertThat(literal.codePoints()).hasSize(1);
    assertThat(literal.codePoints().toArray()).hasSize(1);
```

#### Example

```java
    final String literal = "\uD840\uDC00"; // actually a single character
    assertThat(literal).hasCodePoints(1);
```

**Comment by joel-costigliola** [comment]
I think the best approach here is `assertThat(literal.codePoints()).hasSize(1);`.

`assertThat(literal).hasCodePoints(1);` is misleading, it looks like `[codePoints()](https://docs.oracle.com/javase/8/docs/api/java/lang/CharSequence.html#codePoints--)`  is an integer when it acutally returns a stream of int.

Since `assertThat(intStream)` returns list assertions on the stream content, we already have quite a rich set of assertions and I feel we don't need more here.

**Comment by onacit** [comment]
@joaodelgado Thank you for your kind comments.
