### ISSUE TITLE
mapOf() appears to be in test vs. main; documentation examples won't compile

### ISSUE THREAD

**Issue by joelc** [assertj/assertj-core#2121]
The [documentation](https://assertj.github.io/doc/) contains an example:

```
Map<String, Doctor> doctors = mapOf(entry(drSheldon.name, drSheldon),
                                    entry(drLeonard.name, drLeonard),
                                    entry(drRaj.name, drRaj));
```

`mapOf` is not in the main/production source code. It's in the unit test code: https://github.com/assertj/assertj-core/blob/main/src/test/java/org/assertj/core/test/Maps.java.

As a consumer of the Maven `assertj-core` dependency, I am unable to use `mapOf`.

**Comment by joel-costigliola** [comment]
The point of the javadoc is to illustrate the assertion behavior, in order to do that we use shortcuts for data initialization otherwise most of the code examples would be for setting up data instead of focusing on the assertions.

We will clarify the javadoc but we won't add or expose `mapOf` as it's not the AssertJ's job to provide map factory methods (exposing entry is different in the sense it is used in some assertions parameter).

If you need one I suggest to use guava `ImmutableMap.of` or from Java 9 also [`Map.of`](https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#of-K-V-).
