### ISSUE TITLE
Ignoring non-existing properties

### ISSUE THREAD

**Issue by AhmetTanakol** [assertj/assertj-core#2143]
#### Summary

I couldn't find a way to ignore properties that don't exist in the actual object during recursive comparison. Adding the ignored fields with dummy values to the actual object and setting `ignoreFields` works. Is there a way to skip non-existing properties?

#### Example

```java
        String actualJson = "{ \"id\": null, \"name\": \"Foo\",\"updatedAt\": null }";
        String expectedJson = "{ \"name\": \"Foo\" }";
        String[] ignoreFields = {"id","updatedAt"};
        JsonNode actualResponse = OBJECT_MAPPER.readTree(actualJson);
        JsonNode expectedResponse = OBJECT_MAPPER.readTree(expectedJson);

        RecursiveComparisonConfiguration config = new RecursiveComparisonConfiguration();
        config.ignoreFields(ignoreFields);
        assertThat(actualResponse).usingRecursiveComparison(config).isEqualTo(expectedResponse);
```

**Comment by joel-costigliola** [comment]
for testing json, I recommend JSONUnit, it turns out you can ignore fields in JSON Unit https://github.com/lukas-krecan/JsonUnit#ignoreelements - give it a try and see if it works for you.

**Comment by joel-costigliola** [comment]
This can't be supported as JsonNode is an iterable and the recursive comparison compares iterables by looking at their content since the 2 json nodes have different size (3 vs 1) the comparison fails.

JsonNode and all subtype nodes don't work well with the recursive comparison as everything is an iterable, the recursive comparison won't never compare the node values (for example `IntNode` has a `_value` field but it is not compared as the recursive comparison treats it as an iterable which is empty is this case).
