### ISSUE TITLE
Cannot get ::usingComparatorForFields and ::usingRecursiveComparison to work together in Kotlin

### ISSUE THREAD

**Issue by mahozad** [assertj/assertj-core#2216]
Writing unit tests in Kotlin, the following code does not take into account the comparator specified for Float (Kotiln class) fields:

```kotlin
internal data class Coordinates(val x: Float, val y: Float)
```

```kotlin
val coordinates = Coordinates(1.0f, 2.34f)
Assertions.assertThat(coordinates)
    .usingComparatorForFields(FloatComparator(0.1f), Coordinates::x.name, Coordinates::y.name)
    .usingRecursiveComparison()
    .isEqualTo(Coordinates(1.0f, 2.40f))
```

The above assertion should pass but instead fails with the following error:

> field/property 'y' differ:
> - actual value   : 2.34f
> - expected value : 2.4f
> 
> The recursive comparison was performed with this configuration:
> - no overridden equals methods were used in the comparison (except for java types)
> - these types were compared with the following comparators:
>   - java.lang.Double -> DoubleComparator[precision=1.0E-15]
>   - java.lang.Float -> FloatComparator[precision=1.0E-6]
> - actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).

---

My current workaround is either to use the deprecated ::isEqualToComparingFieldByField or to implement the comparator myself:

### Workaround 1:

```kotlin
Assertions.assertThat(coordinates)
    .usingComparatorForFields(FloatComparator(0.1f), Coordinates::x.name, Coordinates::y.name)
    .isEqualToComparingFieldByField(Coordinates(1.0f, 2.40f))
```

### Workaround 2:

```kotlin
Assertions.assertThat(coordinates)
    .usingComparatorForType(java.util.Comparator { o1, o2 ->
        val epsilon = 0.1f
        return@Comparator if ((o1.toFloat() - o2.toFloat()) < epsilon) 0 else (o1.toFloat() - o2.toFloat()).sign.toInt()
    }, java.lang.Float::class.java)
    .usingRecursiveComparison()
    .isEqualTo(Coordinates(1.0f, 2.40f))
```

Could you please help?

**Comment by joel-costigliola** [comment]
`usingComparatorForFields` is not used in the recursive comparison as stated in https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#usingComparatorForFields(java.util.Comparator,java.lang.String...).

The correct way to go is to use `withEqualsForFields` or `withComparatorForFields` as shown in https://assertj.github.io/doc/#assertj-core-recursive-comparison-comparators.

Workaround 2 works because `usingComparatorForType` is used in the recursive comparison (the javadoc is misleading for this one) but https://www.javadoc.io/static/org.assertj/assertj-core/3.19.0/org/assertj/core/api/AbstractObjectAssert.html#usingRecursiveComparison() says so. Having said that we probably will stop supporting `usingComparatorForType` in the recursive comparison in favor of `withEqualsForType` and in order to have a consistent way of using the recursive comparison API.

**Comment by joel-costigliola** [comment]
@mahozad does that address your concern?

**Comment by mahozad** [comment]
@joel-costigliola Yes. Thank you very much. That solved my problem.
I had posted a thank-you comment on the issue that day but thought you deleted it.
Maybe it was not posted correctly.
Anyway, thank you again.
