### ISSUE TITLE
hasMethods does not work on default methods

### ISSUE THREAD

**Issue by billccn** [assertj/assertj-core#2319]
#### Summary

IMO `hasMethod` should really follow the same contract as `Class.getMethod()`, but it doesn't when it comes to default methods inherited from an interface (that are not overridden with an implementation in the class being asserted).

This is because `org.assertj.core.internal.Classes.getAllMethods(Class<?>)` only looks at parent classes and not any implemented interfaces.

#### Example

```java
class DefaultHasMethodTest {

  interface HasDefault {
    default void method() {}
  }

  static class Impl implements HasDefault {
  }

  @Test
  void testHasMethod() throws Exception {
    assertThat(Impl.class).hasMethods("method");
  }
}
```

This might be related to #880.

**Comment by joel-costigliola** [comment]
Thanks for reporting this, I agree this should be taken into account.

**Comment by scordio** [comment]
Currently, `hasMethods` doesn't follow `Class::getMethods` not only because of ignoring the default methods but also because it looks into non-public methods declared by `actual` or any of its superclasses.

On the other side, `hasDeclaredMethods` looks into the methods of `actual` with any visibility but excluding the inherited ones, in line with `Class::getDeclaredMethods`.

I am wondering if `hasMethods` should only gain interface lookup but still searching for methods of any visibility, or if it should focus only on public methods and be fully aligned with `Class::getMethods`. The latter would be a breaking change but in sync with the JDK behavior.

**Comment by joel-costigliola** [comment]
I think I would go with adding default methods to `hasMethods` and keep looking for methods of any visibility.

We have `hasPublicMethods` that only look at `Class::getMethods`, there is a discrepancy between AssertJ and the JDK here but I feel it is not that bad as `hasPublicMethods` is more obvious than `Class::getMethods` at indicating that it only looks at public methods.

**Comment by scordio** [comment]
I missed `hasPublicMethods`, then yes, I'd add default method lookup to `hasMethods`. I have the fix almost ready so I'll grab it.
