### ISSUE TITLE
Regression in `AbstractMapAssert#containsOnlyKeys` with Spring's `MultiValueMapAdapter`

### ISSUE THREAD

**Issue by ljrmorgan** [assertj/assertj-core#2547]
#### Summary
We saw this when updating from AssertJ 3.19.0 to 3.20.0. It appears that `AbstractMapAssert#containsOnlyKeys` is mutating the map that we're asserting on, which leads to test failures in our case. This is happening on an instance of `org.springframework.util.MultiValueMapAdapter`

#### Example

```java
var underlyingMap = new HashMap<String, List<String>>();
underlyingMap.put("Hello", List.of("World"));

var multiValueMap = CollectionUtils.toMultiValueMap(underlyingMap);
// This assertion passes
assertThat(multiValueMap).containsOnlyKeys("Hello");
// This assertion fails, as `multiValueMap` and `underlyingMap` are now empty
assertThat(multiValueMap).containsOnlyKeys("Hello");
```

The issue seems to have been introduced in #2167, and is caused by [this](https://github.com/assertj/assertj-core/pull/2167/files#diff-abf21eb7e9d518345dcc39f1097da30169084ee0a538e0b174fba36807cf7386R397) use of `Map#remove` on a "clone" of the `Map` being asserted on. In our case that `Map` is a Spring `MultiValueMapAdapter`, which delegates operations to the underlying `Map` that it was constructed from. The `remove` call on the clone delegates to `multiValueMap#remove` which in turn delegates to `underlyingMap#remove`.

**Comment by scordio** [comment]
With a quick look, the only option seems to be performing a check of the fully-qualified class name: if it's `org.springframework.util.MultiValueMapAdapter`, we don't try to clone the map but copy it directly.

**Comment by ljrmorgan** [comment]
Thanks for fixing this so quickly @scordio !

FWIW: I wondered if you might see similar issues in the future with other collection types, I think that approach of wrapping/adapting a collection is quite common (That said, I did try using some of the Apache and Guava collection types and wasn't able to reproduce this with those). I'm not sure what the motivation was for copying/cloning the original collection and then mutating that copy, but I wonder if just taking a set difference of the key set and the set of expected/unexpected keys might be a safer approach?

**Comment by scordio** [comment]
@ljrmorgan the problem started with case insensitive implementations (#2159) and we introduced quite extensive parameterized tests using all implementations we were aware of:

https://github.com/assertj/assertj-core/blob/a124477b203f1816c746c1fb400c60e5079f1209/src/test/java/org/assertj/core/internal/MapsBaseTest.java#L54-L78

It might be we will encounter some other implementations and additional special handling needs to be introduced.

> I wonder if just taking a set difference of the key set and the set of expected/unexpected keys might be a safer approach?

AFAIR using the key set was not good enough with some case insensitive implementations because only `containsKey` has the case insensitive behavior and this is lost once you call `keySet` or `entrySet`.
