### ISSUE TITLE
Improve the performance of `containsExactly` from quadratic to linear complexity

### ISSUE THREAD

**Issue by sarajuhosova** [assertj/assertj-core#2548]
#### Summary

The performance of the `containsExactly` function of `Iterables` is currently quadratic, while it could be linear. It seems to be because of the `IterableDiff` class it uses, which checks the extra and missing elements with an algorithm suitable for checking the elements in any order. However, this is not necessary, since they have to be present in the exact order and so a more efficient linear solution could look something like this:

```java
boolean compare(expected, actual) {
    if (expected.size() != actual.size()) return false;
    for (int i = 0; i < expected.size(); i++) {
       if (expected.get(i) != actual.get(i)) return false;
    }
    return true;
}
```

We ran a scalability analysis on various assertions, which you can find [here](https://desosa2022.netlify.app/projects/assertj/posts/scalability/) if you are interested.

**Comment by joel-costigliola** [comment]
Interesting analysis! Yes `containsExactly` can and should be improved

**Comment by nith2001** [comment]
Can I take this issue?

**Comment by jessicant** [comment]
@nith2001 and I would like to work on this together.

**Comment by joel-costigliola** [comment]
one comment about the issue is that we want to keep the error message as it is.

**Comment by nith2001** [comment]
@joel-costigliola I looked through the *IterableDiff* class and I have question regarding the statement that "they [Iterables] have to be present in the exact order" from @sarajuhosova.

I thought the order in which an Iterable iterates through its Collection does not always have a fixed ordr, right? For example, HashSets. As a result, to check for unexpected elements or additional elements, isn't it necessary to iterate through the whole *expected* iterable to look for an element in *actual*?

**Comment by nith2001** [comment]
Oh wow, never mind, learned something new today
<img width="1085" alt="Screen Shot 2022-04-23 at 11 48 32 PM" src="https://user-images.githubusercontent.com/75632283/164960532-6031618c-708c-4ffa-a554-cad588e30fed.png">
.

**Comment by sarajuhosova** [comment]
I guess here the question also is what the difference for non-ordered datastructures (such as sets) should be between `containsExactly` and `containsExactlyInAnyOrder`. I would argue that to keep the meaning of these the same across all data structures, unordered items should only have the second one 🤔

**Comment by nith2001** [comment]
Hmm, I second your thoughts on this! But interestingly enough, our test suite seems to be using exclusively ArrayLists to test both `containsExactly` and `containsExactlyInAnyOrder`. Making the distinction is pretty important as you said, so that may be something that @joel-costigliola will have give some input on, since it seems to be more of a design decision that is out of my hands :-D

**Comment by nith2001** [comment]
On your statement about iterators, it was my understanding that iterators generally follow an order that is based on the implementation, but whether that order is known by the client or not depends on the nature of the data structure. For example, ArrayList are purposefully designed to have ordering that is clear to the user, while HashSets do not preserve an order that is consistently known by the user in order to prioritize speed over order.

**Comment by joel-costigliola** [comment]
`containsExactly` is not a good fit for some `Set` like `HashSets` (but it's fine for `SortedSets` or `LinkedHashSet`), on this one we expect users to know the semantics of the iterables being tested. If the iteration order is not consistent then the assertion will likely fail and that is fine since the iterable did not honor the assertion contract.

`containsExactlyInAnyOrder` can be used with `HashSet` aspointed out by @sarajuhosova. 

> Plus, it seems that that IterableDiff_Test lacks testing with iterables that aren't ArrayLists where the ordering could be different, like HashSets.

I agree that we could have used different iterable types but only those with consistent iteration order (so no `HashSet`).

In my experience we should not rely on `HashSet` iteration even though it could look consistent, I remember on one project tests that relied on this and failed once we migrated to a newer version of java that changes the underlying `HashSet` iteration order.

So moving forward, we should continue treating iterable as if they had a consistent iteration order for `containsExactly` and let users the responsibility to choose the correct assertion for `HashSet`, what we can do though is to enhance the javadoc with a warning to prefer `containsExactlyInAnyOrder` over `containsExactly` for `HashSet` or any iterable whose iteration order is not predictable.

**Comment by nith2001** [comment]
So then to be clear, given the following two iterables:
`actual = [0, 1, 2, 3, 4, 5]`
`expected = [9, 9, 0, 1, 2, 3, 4]`

What would be the resulting unexpected actual list and missing actual list with these new changes?
My guess was:
unexpected actual list = [5]
missing actual list = [9, 9]

But I'm not so sure anymore since my head's kinda boggled right now.

**Comment by joel-costigliola** [comment]
that assertion would fail at the first element (that's the main reason), then to be helpful we do a diff of the iterables with the result you have suggested @nith2001.

**Comment by nith2001** [comment]
Hmmm, so if I tried implementing the IterableDiff to follow this solution, it would require the look ahead of actual iterable and remove values from it in future indices, which seems to be the problem causing slower runtime. As a result, if we needed to improve from O(n^2) to O(n) on the error handling, then there might need to be some compromise on how accurate the error handling will be. 

I'll keep try to hack away at an O(n) solution though!

**Comment by joel-costigliola** [comment]
I don't think it is important that the error handling be O(n), I don't even think it is possible.
Rationale being that tests should succeed most of the time, if they fail it's ok to take a bit more time to provide a good error message.

**Comment by nith2001** [comment]
But...wasn't the reason why the code was running at O(n^2) solely because of the IterableDiff class?

**Comment by nith2001** [comment]
@sarajuhosova Yeah, that's probably the case. But even with succeeding iterables, the IterableDiff class is built before hand, so even with matching iterables, the runtime will still be O(n^2). It will be a bit odd to try and fix this while maintaining the error handling behavior.

**Comment by nith2001** [comment]
Here's what the containsExactly used to be:
```
public void assertContainsExactly(AssertionInfo info, Iterable<?> actual, Object[] values) {
    checkIsNotNull(values);
    assertNotNull(info, actual);

    List<Object> actualAsList = newArrayList(actual);
    IterableDiff<Object> diff = diff(actualAsList, asList(values), comparisonStrategy);
    if (!diff.differencesFound()) {
      // actual and values have the same elements but are they in the same order ?
      int i = 0;
      // use actualAsList instead of actual in case actual is a singly-passable iterable
      for (Object elementFromActual : actualAsList) {
        if (!areEqual(elementFromActual, values[i])) {
          throw failures.failure(info, elementsDifferAtIndex(elementFromActual, values[i], i, comparisonStrategy));
        }
        i++;
      }
      return;
    }
    throw failures.failure(info,
                           shouldContainExactly(actual, asList(values), diff.missing, diff.unexpected,
                                                comparisonStrategy));
  }


Here's what I'm thinking it could be:
```
public void assertContainsExactly(AssertionInfo info, Iterable<?> actual, Object[] values) {
    checkIsNotNull(values);
    assertNotNull(info, actual);

    List<Object> actualAsList = newArrayList(actual);
    // actual and values have the same elements but are they in the same order ?
    int i = 0;
    // use actualAsList instead of actual in case actual is a singly-passable iterable
    for (Object elementFromActual : actualAsList) {
      if (!areEqual(elementFromActual, values[i])) {
        throw failures.failure(info, elementsDifferAtIndex(elementFromActual, values[i], i, comparisonStrategy));
      }
      i++;
    }
    throw failures.failure(info,
                           shouldContainExactly(actual, asList(values), diff.missing, diff.unexpected,
                                                comparisonStrategy));
  }
```

**Comment by sarajuhosova** [comment]
I feel like you could still first check the order and pass if it’s correct. If it’s wrong, you remember the index and only then instantiate diff. It if finds no differences in elements, you return the index you remembered. That way you just move the loop in front of the diff and provide an efficient exit if they are equal.

**Comment by nith2001** [comment]
```
public void assertContainsExactly(AssertionInfo info, Iterable<?> actual, Object[] values) {
    checkIsNotNull(values);
    assertNotNull(info, actual);

    List<Object> actualAsList = newArrayList(actual);

    // length check
    if (actualAsList.size() != values.length) {
      IterableDiff<Object> diff = diff(actualAsList, asList(values), comparisonStrategy);
      throw failures.failure(info,
        shouldContainExactly(actual, asList(values), diff.missing, diff.unexpected,
          comparisonStrategy));
    }

    // actual and values have the same number elements but are they equivalent and in the same order?
    int i = 0;
    // use actualAsList instead of actual in case actual is a singly-passable iterable
    for (Object elementFromActual : actualAsList) {
      // if the objects are not equal, begin the error handling process
      if (!areEqual(elementFromActual, values[i])) {
        IterableDiff<Object> diff = diff(actualAsList, asList(values), comparisonStrategy);
        if (diff.differencesFound()) {
          throw failures.failure(info,
            shouldContainExactly(actual, asList(values), diff.missing, diff.unexpected,
              comparisonStrategy));
        } else {
          throw failures.failure(info, elementsDifferAtIndex(elementFromActual, values[i], i, comparisonStrategy));
        }
      }
      i++;
    }
    // If here, then done!
  }
```

**Comment by nith2001** [comment]
Interestingly enough it passes our test suite :-D

**Comment by joel-costigliola** [comment]
The code looks ok @nith2001, I would refactor it a bit by using a for loop with index (so no need to handle `i`), extract a method to build the failure with diff and remove an unnecessary `else` block, something like:

```java
public void assertContainsExactly(AssertionInfo info, Iterable<?> actual, Object[] values) {
    checkIsNotNull(values);
    assertNotNull(info, actual);

    List<Object> actualAsList = newArrayList(actual);

    // length check
    if (actualAsList.size() != values.length) {
      IterableDiff<Object> diff = diff(actualAsList, asList(values), comparisonStrategy);
      throw buildShouldContainExactlyWithDiffAssertionError(diff, actual, values, info);
    }

    // actual and values have the same number elements but are they equivalent and in the same order?
    // use actualAsList instead of actual in case actual is a singly-passable iterable
    for (int i = 0; i < values.length; i++) {
      if (!areEqual(elementFromActual, values[i])) {
        // we have an error, it can be in the order of values or that some values differ, if values differ we want to report the diff.
        IterableDiff<Object> diff = diff(actualAsList, asList(values), comparisonStrategy);
        if (diff.differencesFound()) {
          throw buildShouldContainExactlyWithDiffAssertionError(diff, actual, values, info);
        } 
        // error was just in the order or values, report the first discrepancy
        throw failures.failure(info, elementsDifferAtIndex(elementFromActual, values[i], i, comparisonStrategy));
      }
    }
    // If here, then done!      
  }

private static AssertionError buildShouldContainExactlyWithDiffAssertionError(diff, actual, values, info) {
   return failures.failure(info, shouldContainExactly(actual, asList(values), diff.missing, diff.unexpected, comparisonStrategy));
}
```
I have written the code above without an IDE so there might be some syntax errors, I feel it's readable, we want to add a comment to say that the success path is O(n) while the error is O(n2) as that's ok since errors should be rare

**Comment by nith2001** [comment]
Thanks @joel-costigliola ! I'll probably get to fixing my coffee during this week after my last midterm.

**Comment by nith2001** [comment]
@joel-costigliola Seems like the newArrayList function is being used a lot in Iterables.java, is that okay?

**Comment by joel-costigliola** [comment]
it's probably for another issue, it `list` was introduced after `newArrayList`, we now prefer to use `list` and refactor when we change a piece of code.

**Comment by nith2001** [comment]
Dope! All done then, just need to merge I think.
