### ISSUE TITLE
Fix javadoc style on java 17

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2576]
#### Summary

The javadoc generated style is broken in java 17

#### Actual 

![image](https://user-images.githubusercontent.com/382613/163735532-68a27fb9-53ea-4576-b84c-283a24cadccc.png)

#### Expected outcome

* https://www.javadoc.io/doc/org.assertj/assertj-core/3.21.0/index.html
* https://www.javadoc.io/doc/org.assertj/assertj-core/3.21.0/org/assertj/core/api/AbstractIterableAssert.html#containsExactlyInAnyOrderElementsOf(java.lang.Iterable)

**Comment by scordio** [comment]
We may need to do something similar to https://github.com/assertj/assertj-core/pull/1600#issuecomment-529258937.

However, this would require bumping the Java used in the release workflow to 17, which is currently not an option due to assertj/assertj-parent-pom#115.

This could be a blocker for AssertJ 4.

**Comment by joel-costigliola** [comment]
Yeah it's for AssertJ 4, I'll put the label

**Comment by joel-costigliola** [comment]
on it!

**Comment by scordio** [comment]
@joel-costigliola yes, I made just a small progress yesterday: I generated the new stylesheet and started customizing it like the current one, but there are CSS elements that are no longer in the Java 17 stylesheet so I'd need a bit of trial and error.

I could continue later in the day, but happy to leave it if you prefer to jump on it.

If it turns out it's a big effort, we could put this aside and downgrade the Java version to 11 for the release workflow.
