### ISSUE TITLE
containsExactlyInAnyOrderEntriesOf() is broken

### ISSUE THREAD

**Issue by sofax** [assertj/assertj-core#2710]
#### Summary
_containsExactlyInAnyOrderEntriesOf()_ is broken (and has been since, at least, v3.20.0). The example below should not throw an assertion exception, but it yields:

```
java.lang.AssertionError: 
Expecting map:
  {"a"=["v.a"]}
to contain only:
  ["a"=["v.a"]]
but the following map entries were unexpected:
  ["a"=[["v.a"]]]
```

#### Example

```java
      final MultivaluedMap<String, String> map = new MultivaluedHashMap<>();
      map.putSingle( "a", "v.a" );
      assertThat( map ).containsExactlyInAnyOrderEntriesOf( map );
```

Tested with v3.20.0, v3.23.1.

**Comment by scordio** [comment]
The issue is triggered in the [`clone`](https://github.com/assertj/assertj-core/blob/7ccc197688f1c5cf936df07fcda19d9ab2d0c2d5/src/main/java/org/assertj/core/internal/Maps.java#L421-L441) method when we try to clone the input map, specifically here:

https://github.com/assertj/assertj-core/blob/7ccc197688f1c5cf936df07fcda19d9ab2d0c2d5/src/main/java/org/assertj/core/internal/Maps.java#L431

Since `MultivaluedHashMap` has two copying constructors, one expecting `Map` and the other expecting `MultivaluedHashMap`, most likely we are calling the one expecting `Map` which does an additional `List` wrapping around each input value.

I'll check if we can fix it by simply changing the parameter of `getConstructor`.
