### ISSUE TITLE
Return from to train calls

### ISSUE THREAD

**Issue by lordofthejars** [assertj/assertj-core#985]
#### Summary

`return` option added in AssertJ 2.7.0 uses *onion* calls (like _Hamcrest_) instead of what usually uses _assertj_ which is *train* calls.

The idea of `return` is really nice but could it be reworked? Maybe you've already thought about it and there are some hard reasons to do it in that way. 

#### Example

```java
assertThat(mozart).returns("Wolfgang Amadeus Mozart").for(Composer::getName);
```
I have not deeply see if this is breaking something, but before sending a PR, I would like to know your opinion.

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
This is a fair point.
In the actual implementation `from` is optional, it's only syntactic sugar, i.e you can write:
```java
assertThat(mozart).returns("Wolfgang Amadeus Mozart", Composer::getName);
```
Following your suggestion (but using `from` instead of `for`) would make the API easier to use as `from` would be the only possible call to chain after `returns`, one drawback though is that if you forget to call `from` then you are not asserting anything (can be mitigated by annotating `returns` with `@CheckReturnValue` to let findbugs detect it), this can't happen with the current implementation.

There are  a few places where AssertJ uses one level onion call, I think one level is acceptable even though not so easy to remember (which is like _Hamcrest_ pain) thus I have a slight preference for your suggestion but I'd like to hear more opinions before deciding anything.

@PascalSchumacher, @Mura-Mi what are your thoughts ?

For the sake of the discussion, here's what we could add using @lordofthejars  example with `from`:

```java
assertThat(mozart).returns("Wolfgang Amadeus Mozart").from(Composer::getName);
```

**Comment by Mura-Mi** [comment]
I originally planned to implement API like @lordofthejars suggests.

Another drawback for that idea is that it would be a little complex implementation to return `Assert<Composer>` from `from` method for that example. The merit of AssertJ is chaining assertion, so I agree to this suggestion if `from` method can return `Assert<S, A>`.

```java
assertThat(mozart)
        .returns("Wolfang Amadeus Mozart").from(Composer::getName)
        .returns(LocalDate.of(1756, 1, 27)).from(Composer::getBirthday)
```

**Comment by nach-o-man** [comment]
As frequent user of this method I don't really see much point in this,mostly because current api it is consistent.
@lordofthejars @joel-costigliola @Mura-Mi  do you assume there can be any other methods apart from `from` to be following 'returns'?

**Comment by joel-costigliola** [comment]
I feel there is not enough value doing this in regard to the effort involved.
